<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>CleanTool.UI</RootNamespace>
    <AssemblyName>CleanTool</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanTool.Core\CleanTool.Core.csproj" />
    <ProjectReference Include="..\CleanTool.Rules\CleanTool.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZeroUI.Wpf" Version="1.5.0" />
  </ItemGroup>
</Project>
