<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CleanTool.Rules</RootNamespace>
    <AssemblyName>CleanTool.Rules</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CleanTool.Core\CleanTool.Core.csproj" />
  </ItemGroup>
</Project>
