<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ZeroClean.Rules</RootNamespace>
    <AssemblyName>ZeroClean.Rules</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroClean.Core\ZeroClean.Core.csproj" />
  </ItemGroup>
</Project>
