<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>ZeroClean.UI</RootNamespace>
    <AssemblyName>ZeroClean</AssemblyName>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZeroClean.Core\ZeroClean.Core.csproj" />
    <ProjectReference Include="..\ZeroClean.Rules\ZeroClean.Rules.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ZeroUI.Wpf" Version="1.5.0" />
  </ItemGroup>
</Project>
