using ZClean.Core.Models;

namespace ZClean.Rules.System;

/// <summary>
/// Cleans Windows Error Reporting (WER) queue, archive, and report files.
/// </summary>
public class WindowsErrorReportingRule : BaseFolderRule
{
    public override string Id => "sys.wer";
    public override string Name => "Windows Error Reports (WER)";
    public override string Description => "Cleans archived telemetry and error reports generated by Windows Error Reporting.";
    public override CleanCategory Category => CleanCategory.System;
    public override CleanRiskLevel RiskLevel => CleanRiskLevel.Safe;
    public override bool IsDefaultEnabled => true;

    protected override IEnumerable<string> GetTargetDirectories()
    {
        var localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        var userWer = Path.Combine(localAppData, "Microsoft", "Windows", "WER");
        if (Directory.Exists(userWer))
            yield return userWer;

        var commonAppData = Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData);
        var machineWer = Path.Combine(commonAppData, "Microsoft", "Windows", "WER");
        if (Directory.Exists(machineWer))
            yield return machineWer;
    }
}
