using CleanTool.Core.Models;

namespace CleanTool.Rules.System;

/// <summary>
/// Cleans crash dumps generated by Windows Error Reporting and application faults.
/// </summary>
public class CrashDumpsRule : BaseFolderRule
{
    public override string Id => "sys.crashdumps";
    public override string Name => "Crash & Memory Dumps";
    public override string Description => "Cleans post-mortem crash dump files (*.dmp) in LocalAppData and Windows Minidump.";
    public override CleanCategory Category => CleanCategory.System;
    public override CleanRiskLevel RiskLevel => CleanRiskLevel.Safe;
    public override bool IsDefaultEnabled => true;

    protected override IEnumerable<string> GetTargetDirectories()
    {
        var localAppData = Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData);
        var crashDumps = Path.Combine(localAppData, "CrashDumps");
        if (Directory.Exists(crashDumps))
            yield return crashDumps;

        var winDir = Environment.GetFolderPath(Environment.SpecialFolder.Windows);
        var minidump = Path.Combine(winDir, "Minidump");
        if (Directory.Exists(minidump))
            yield return minidump;
    }
}
